nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:4200'] 
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE'] 
        max_age: 3600
    paths:
        '^/bands/all/': 
            allow_origin: ['*'] 
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
        '^/': 
            allow_origin: ['*'] 
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
