nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:4200'] 
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['POST', 'OPTIONS', 'GET']
        expose_headers: []
        max_age: 3600
    paths:
        '^/': ~
